server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shortener}
    username: ${DB_USER:shortener}
    password: ${DB_PASSWORD:shortener}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 1500
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 400ms
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      properties:
        enable.idempotence: true
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: record

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

shortener:
  base-url: ${SHORT_BASE_URL:http://localhost:8080}
  code-length: 8
  max-collision-retries: 5
  l1-ttl: 30s
  redis-max-ttl: 30m
  negative-cache-ttl: 20s
  max-expiration: 1825d
  create-requests-per-minute: 60
  reserved-aliases: [api, admin, health, metrics, actuator, swagger, docs]

resilience4j:
  circuitbreaker:
    instances:
      redis:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      redisRateLimit:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
